channels:
  - conda-forge
dependencies:
  - python=3.6
  - appmode
  - os
  - io
  - glob
  - re
  - datetime
  - pandas
  - scipy
  - numpy
  - math
  - pathlib
  - matplotlib.ticker
  - seaborn
  - matplotlib
  - matplotlib.pyplot
  - matplotlib.gridspec
  - scipy.stats
  - datetime
  - ipywidgets
  - ipywidgets
  - IPython.display
  - CentralAge
